### ISSUE TITLE
Form API

### ISSUE THREAD

**Issue by noahlange** [overlandjs/overland#2]
All right, forms are currently a bit dicey. The only major entry in this space is [https://github.com/caolan/forms](https://github.com/caolan/forms), and it's kind of... challenging to work with. I wrote a wrapper around it briefly, but it was not really worth the time investment. Looking for something a bit sturdier and ideally, class-based.

So we're probably going to have to roll our own.

## Form Creation
Ideally we'll have a very similar API between Forms and ModelForms, the distinction being that a Form is a collection of widgets unattached to a specific Model instance, whereas a ModelForm automates the widget creation process but is attached to a specific model. For this issue we're discussing standard Forms only.

So there are three different API models I'm envisioning. I'm not thrilled with any of them. We need to store four different bits of information about each Widget and do it in the least frictiony way possible.

- name: i.e., name attribute
- label: i.e., form label
- type: tel, text, textarea, etc.
- field?: database field, if appropriate

#### Option 1
We use a simple JS object, where name corresponds to the name in the JS object and the label/type/field are stored with the Widget constructor.

**PROS** 
  - simple to use
  - less ugly than 2B

**CONS**
  - ordering is ~~arbitrary, because key order cannot be guaranteed~~ arbitrary in theory, ordered by insertion in practice. Thanks @insin!
  
This is a major con.

```typescript
class MyForm extends Form {
  public widgets = {
    tel: new TelephoneWidget('Your telephone'),
    email: new EmailWidget('Your Email'),
    fooStatus: new SelectWidget('Foobar Status', [
      { label: 'foo', value: 'bar' }  
    ])
  };
}

const myForm = new Form({
  tel: new TelephoneWidget('Your telephone'),
  email: new EmailWidget('Your Email'),
  fooStatus: new SelectWidget('Foobar Status', [
    { label: 'foo', value: 'bar' }  
  ])
});
```

#### Option 2A
We use a JS array and stuff all the other information into the widget constructor via positional arguments.

**PROS**
- compact, but less compact than 1
- less ugly and verbose than 2B

**CONS**
- positional arguments without autocomplete are pains in the ass

```typescript
class MyForm extends Form {
  public widgets = [
    new TelephoneWidget('Your telephone', 'tel'),
    new EmailWidget('Your Email', 'email'),
    new SelectWidget('Foobar Status', 'foobar', [
      { label: 'foo', value: 'bar' }
    ])
  ];
}

const myForm = new Form([
  new TelephoneWidget('Your telephone', 'tel'),
  new EmailWidget('Your Email', 'email'),
  new SelectWidget('Foobar Status', 'foobar', [
    { label: 'foo', value: 'bar' }
  ])
]);
```

#### Option 2B
We use a JS Array and stuff all the other information into the widget constructor via an object hash.

**PROS**
- super explicit
- no argument confusion

**CONS**
- verbose as all get-out

```typescript
class MyForm extends Form {
  public widgets = [
    new TelephoneWidget({
      name: 'tel',
      label: 'Your telephone'
    }),
    new EmailWidget({
      name: 'email',
      label: 'Your email'
    }),
    new SelectWidget({
      name: 'foobar',
      label: 'Foobar status',
      choices: [
        { label: 'foo', value: 'bar' }
      ]
    })
  ];
}

const myForm = new Form([
  new TelephoneWidget({
    name: 'tel',
    label: 'Your telephone'
  }),
  new EmailWidget({
    name: 'email',
    label: 'Your email'
  }),
  new SelectWidget({
    name: 'foobar',
    label: 'Foobar status',
    choices: [
      { label: 'foo', value: 'bar' }
    ]
  })
]);
```

## Form Binding and Validation
Obviously, binding data is important, probably as important as outputting the form itself. I'm thinking the API will look something like this:

```typescript
const data = {
  tel: '555-555-5555',
  email: 'random@email.com',
  foobar: 'bar'
};
const myForm = new MyForm(data)
// - or alternatively, assuming we went with creation API 2 -
myForm.bind(data);
```

You can see that the class-based API is quite nice here, because the form structure is built into the form object instead of tossed in at runtime.

Validation and retrieval of coerced data would look something like this.

```typescript
const valid = form.isValid();
const data = form.data;
```

## Form Rendering
Because select options will be entered into the form structure, I think the standard form's `form.toHTML()` call can be synchronous. Unfortunately, a ModelForm's `toHTML()` call cannot be, because it will need to query data to populate relations at runtime.

For this reason, I'm *tempted* to wrap the former into a `Promise.resolve()` so it can be used "asychronously" for both form types. A newbie probably would get confused if some kinds of forms needed to be `await`ed when rendered and others didn't.

At any rate, the API will look *something* like this, again depending on which API was chosen.

```typescript
const form = new MyForm(data);
const html = await form.toHTML();
// -or-
const form = myForm.bind(data);
const html = await form.toHTML();
```

**Comment by insin** [comment]
For Option 1, ordering is arbitrary according to the ES5 spec, but was ordered in practice apart from numeric keys.

The ES6 spec [defines the algorithm](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) which was previously being used (TL;DR: numeric properties always appear first, rest in insertion order, and I'm assuming you don't care about Symbols).

I depended on key ordering without issue when porting most of `django.forms` (without all the ModelForms stuff) to JavaScript: https://github.com/insin/newforms

**Comment by noahlange** [comment]
Really good to know, thanks.

I'm not really in the react world so I hadn't seen your library, but I'll definitely take a look. Cheers!
